hotel/Models/ViewModels/RoomsGroupViewModel.cs
using Hotel.Models.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace hotel.Models.ViewModels
{
    public class RoomsGroupViewModel
    {
        [Display(Name = "کد گروه اتاق")]
        public int RoomsGroupId { get; set; }
        [Required]
        [MaxLength(200)]
        [Display(Name = "عنوان گروه اتاق")]
        public string RoomsGroupTitle { get; set; }
        [Required]
        [Display(Name = "توضیحات مدل اتاق")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        [MaxLength(100)]
        [Display(Name = "تصویر")]
        public string ImageName { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual IEnumerable<Rooms> Rooms { get; set; }
    }
}

hotel/Areas/Admin/Controllers/RoomsGroupsController.cs
using hotel.Models.ViewModels;
using Hotel.Models.Context;
using Hotel.Models.Models;
using Hotel.Service.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace hotel.Areas.Admin.Controllers
{
    public class RoomsGroupsController : Controller
    {
        // GET: Admin/RoomsGroups

        private DbHotelContext db = new DbHotelContext();
        RoomsGroupService _roomsGroupService;
        public RoomsGroupsController()
        {
            _roomsGroupService = new RoomsGroupService(db);
        }

        public ActionResult Index()
        {
            var roomsGroups = _roomsGroupService.GetAll();
            var roomsGroupViewModels = AutoMapperConfig.mapper.Map<IEnumerable<RoomsGroup>, List<RoomsGroupViewModel>>(roomsGroups);

            return View(roomsGroupViewModels);
        }

        // GET: Admin/RoomsGroups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomsGroup roomsGroup = _roomsGroupService.GetEntity(id.Value);
            if (roomsGroup == null)
            {
                return HttpNotFound();
            }
            var roomsGroupViewModel = AutoMapperConfig.mapper.Map<RoomsGroup, RoomsGroupViewModel>(roomsGroup);
            return View(roomsGroupViewModel);
        }

        // GET: Admin/RoomsGroups/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/RoomsGroups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RoomsGroupTitle , RoomsGroupId , Description")] RoomsGroupViewModel roomsGroupViewModel, HttpPostedFileBase imgUpload)
        {
            if (ModelState.IsValid)
            {
                string imageName = "nophoto.png";
                if (imgUpload != null)
                {
                    imageName = Guid.NewGuid().ToString().Replace("-", "") + System.IO.Path.GetExtension(imgUpload.FileName);
                    imgUpload.SaveAs(Server.MapPath("/images/rooms-group/") + imageName);
                }
                roomsGroupViewModel.ImageName = imageName;
                roomsGroupViewModel.RoomsGroupId = _roomsGroupService.NextRoomsGroupId();
                RoomsGroup roomsGroup = AutoMapperConfig.mapper.Map<RoomsGroupViewModel, RoomsGroup>(roomsGroupViewModel);
                _roomsGroupService.Add(roomsGroup);
                _roomsGroupService.Save();
                return RedirectToAction("Index");
            }

            return View(roomsGroupViewModel);
        }

        // GET: Admin/RoomsGroups/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomsGroup roomsGroup = _roomsGroupService.GetEntity(id.Value);
            if (roomsGroup == null)
            {
                return HttpNotFound();
            }
            var roomsGroupViewModel = AutoMapperConfig.mapper.Map<RoomsGroup, RoomsGroupViewModel>(roomsGroup);
            return View(roomsGroupViewModel);
        }

        // POST: Admin/RoomsGroups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RoomsGroupId,RoomsGroupTitle,ImageName,Description")] RoomsGroupViewModel roomsGroupViewModel, HttpPostedFileBase imgUpload)
        {
            if (ModelState.IsValid)
            {
                if (imgUpload != null)
                {
                    if (roomsGroupViewModel.ImageName != "nophoto.png")
                    {
                        System.IO.File.Delete(Server.MapPath("/images/rooms-group/") + roomsGroupViewModel.ImageName);
                    }
                    else
                    {
                        roomsGroupViewModel.ImageName = Guid.NewGuid().ToString().Replace("-", "") + System.IO.Path.GetExtension(imgUpload.FileName);
                    }
                    imgUpload.SaveAs(Server.MapPath("/images/rooms-group/") + roomsGroupViewModel.ImageName);
                }
                RoomsGroup roomsGroup = AutoMapperConfig.mapper.Map<RoomsGroupViewModel, RoomsGroup>(roomsGroupViewModel);
                _roomsGroupService.Update(roomsGroup);
                _roomsGroupService.Save();
                return RedirectToAction("Index");
            }
            return View(roomsGroupViewModel);
        }

        // GET: Admin/RoomsGroups/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomsGroup roomsGroup = _roomsGroupService.GetEntity(id.Value);
            if (roomsGroup == null)
            {
                return HttpNotFound();
            }
            var roomsGroupViewModel = AutoMapperConfig.mapper.Map<RoomsGroup, RoomsGroupViewModel>(roomsGroup);
            return View(roomsGroupViewModel);
        }

        // POST: Admin/RoomsNewsGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var roomsGroup = _roomsGroupService.GetEntity(id);
            _roomsGroupService.Delete(id);
            _roomsGroupService.Save();
            if (roomsGroup.ImageName != "nophoto.png")
            {
                System.IO.File.Delete(Server.MapPath("/images/rooms-group/") + roomsGroup.ImageName);
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            _roomsGroupService.Dispose();
        }
    }
}

hotel/Areas/Admin/Views/RoomsGroups/Create.cshtml
@model hotel.Models.ViewModels.RoomsGroupViewModel
@{
    ViewBag.Title = "Create";
}

<h2>ایجاد نوع جدید اتاق</h2>



@using (Html.BeginForm("Create", "RoomsGroups", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true)

    <div class="form-group">
        @Html.LabelFor(model => model.RoomsGroupTitle, new { @class = "control-label col-md-4" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RoomsGroupTitle)
            @Html.ValidationMessageFor(model => model.RoomsGroupTitle)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ImageName, new { @class = "control-label col-md-4" })
        <div class="col-md-10">
            <img src="/images/rooms-group/nophoto.png" class="img60x60" id="impPrev" />
            <input type="file" id="imgupload" name="imgUpload" onchange="showPreview(this)" value="nophoto.png" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-4" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="درج رکورد " class="btn btn-success" /> |
            @Html.ActionLink("برگشت به لیست ", "Index", null, new { @class = "btn btn-primary" })
        </div>
    </div>
</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/main-script.js"></script>
}

hotel/Areas/Admin/Views/RoomsGroups/Delete.cshtml
@model hotel.Models.ViewModels.RoomsGroupViewModel
@{
    ViewBag.Title = "Delete";
}

<h2>حذف </h2>

<h3>آیا برای حذف این نوع اتاق اطمینان دارید؟</h3>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RoomsGroupTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoomsGroupTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>


        <dd>
            <img src="/images/rooms-group/@Model.ImageName" class="img120x120" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="حذف " class="btn btn-danger" /> |
            @Html.ActionLink("برگشت به لیست", "Index", null, new { @class = "btn btn-primary" })
        </div>
    }
</div>

hotel/Areas/Admin/Views/RoomsGroups/Details.cshtml
@model hotel.Models.ViewModels.RoomsGroupViewModel
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RoomsGroupTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoomsGroupTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>

        <dd>
            <img src="/images/rooms-group/@Model.ImageName" class="img120x120" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("ویرایش", "Edit", new { id = Model.RoomsGroupId }, new { @class = "btn btn-warning" }) |
    @Html.ActionLink("برگشت به لیست", "Index", null, new { @class = "btn btn-primary" })
</p>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/main-script.js"></script>
}

hotel/Areas/Admin/Views/RoomsGroups/Edit.cshtml
@model hotel.Models.ViewModels.RoomsGroupViewModel
@{
    ViewBag.Title = "Edit";
}


<h2>ویرایش نوع اتاق</h2>



@using (Html.BeginForm("Edit", "RoomsGroups", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.RoomsGroupId)
    @Html.HiddenFor(model => model.ImageName)
    @Html.HiddenFor(model => model.Description)
    <div class="form-group">
        @Html.LabelFor(model => model.RoomsGroupTitle, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RoomsGroupTitle)
            @Html.ValidationMessageFor(model => model.RoomsGroupTitle)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ImageName, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <img src="/images/rooms-group/@Model.ImageName" class="img60x60" id="impPrev" />
            <input type="file" id="imgupload" name="imgUpload" onchange="showPreview(this)" />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="ذخیره تغییرات" class="btn btn-warning" /> |
            @Html.ActionLink("برگشت به لیست", "Index", null, new { @class = "btn btn-primary" })
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/main-script.js"></script>
}

hotel/Areas/Admin/Views/RoomsGroups/Index.cshtml
@model IEnumerable<hotel.Models.ViewModels.RoomsGroupViewModel>

@{
    ViewBag.Title = "انواع اتاق ها";
}

<h2>لیست انواع اتاق ها</h2>

<p>
    @Html.ActionLink("درج نوع اتاق جدید", "Create", null, new { @class = "btn btn-success btn-xs" })
</p>
<table class="table">
    <tr>
        <th class="col-md-1">
            @Html.DisplayNameFor(model => model.RoomsGroupId)
        </th>
        <th class="col-md-1">
            @Html.DisplayNameFor(model => model.ImageName)
        </th>
        <th class="col-md-2">
            @Html.DisplayNameFor(model => model.RoomsGroupTitle)
        </th>
        <th class="col-md-5">
            @Html.DisplayNameFor(model => model.Description)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td class="col-md-1">
                @Html.DisplayFor(modelItem => item.RoomsGroupId)
            </td>
            <td class="col-md-1">
                <img src="~/images/rooms-group/@item.ImageName" class="img60x60" />

            </td>
            <td class="col-md-2">
                @Html.DisplayFor(modelItem => item.RoomsGroupTitle)
            </td>
            <td class="col-md-5">
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("ویرایش", "Edit", new { id = item.RoomsGroupId }, new { @class = "btn btn-warning btn-xs" }) |
                @Html.ActionLink("جزئیات", "Details", new { id = item.RoomsGroupId }, new { @class = "btn btn-info btn-xs" }) |
                @Html.ActionLink("حذف", "Delete", new { id = item.RoomsGroupId }, new { @class = "btn btn-danger btn-xs" })
            </td>
        </tr>
    }

</table>