hotel/Models/ViewModels/CommentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Hotel.Models.Models;

namespace hotel.Models.ViewModels
{
    public class CommentViewModel
    {
        [Display(Name = "کد نظر")]
        public int CommentId { get; set; }
        [Required]
        [MaxLength(2000)]
        [Display(Name = "متن نظر")]
        [DataType(DataType.MultilineText)]
        public string CommentText { get; set; }
        [Required]
        [MaxLength(20)]
        [Display(Name = "نام کاربر")]
        public string Name { get; set; }
        [Required]
        [MaxLength(30)]
        [Display(Name = "ایمیل")]
        [DataType(DataType.EmailAddress, ErrorMessage = "قالب ایمیل صحیح نمیاشد")]
        public string Email { get; set; }
        [Display(Name = "تاریخ ثبت نظر")]
        public DateTime RegisterDate { get; set; }
        [Required]
        [Display(Name = "وضعیت نظر")]
        public bool IsActive { get; set; }
        [Display(Name = "کد اتاق")]
        public int RoomsGroupId { get; set; }

        public virtual RoomsGroup RoomsGroup { get; set; }
    }
}

hotel/Areas/Admin/Controllers/CommentsController.cs
using hotel.Models.ViewModels;
using Hotel.Models.Context;
using Hotel.Models.Models;
using Hotel.Service.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace hotel.Areas.Admin.Controllers
{
    public class CommentsController : Controller
    {
        private DbHotelContext db = new DbHotelContext();
        CommentService _commentService;
        public CommentsController()
        {
            _commentService = new CommentService(db);
        }
        public ActionResult Index()
        {
            var comments = _commentService.GetAll();
            var commentViewModel = AutoMapperConfig.mapper.Map<IEnumerable<Comment>, List<CommentViewModel>>(comments);
            return View(commentViewModel);
        }

        // GET: Admin/Comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }


        // GET: Admin/Comments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = _commentService.GetEntity(id.Value);
            if (comment == null)
            {
                return HttpNotFound();
            }
            var commentViewModel = AutoMapperConfig.mapper.Map<Comment, CommentViewModel>(comment);
            return View(commentViewModel);
        }

        // POST: Admin/Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CommentId,CommentText,Name,Email,RegisterDate,IsActive,RoomsGroupId")] CommentViewModel commentViewModel)
        {
            if (ModelState.IsValid)
            {
                var comment = AutoMapperConfig.mapper.Map<CommentViewModel, Comment>(commentViewModel);
                _commentService.Update(comment);
                _commentService.Save();
                return RedirectToAction("Index");
            }

            return View(commentViewModel);
        }

        // GET: Admin/Comments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Admin/Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

hotel/Controllers/CommentController.cs
using hotel.Models.ViewModels;
using Hotel.Models.Context;
using Hotel.Models.Models;
using Hotel.Service.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hotel.Controllers
{
    public class CommentController : Controller
    {
        DbHotelContext db = new DbHotelContext();
        CommentService _commentService;

        public CommentController()
        {
            _commentService = new CommentService(db);
        }
        public ActionResult ShowComments() 
        {
            var comments=_commentService.GetAll().Where(t => t.IsActive ).OrderByDescending(u=>u.CommentId).ToList();
            var commentViewModels=AutoMapperConfig.mapper.Map<IEnumerable<Comment>, List<CommentViewModel>>(comments);
            return PartialView(commentViewModels);
        }

        public ActionResult CreateComment() 
        {
            var commentViewModels = new CommentViewModel();
            return PartialView(commentViewModels);
        }

        [HttpPost]
        public ActionResult CreateComment([Bind(Include = "Name,Email,CommentText")] CommentViewModel commentViewModel)   
        {
            if(ModelState.IsValid)
            {
                Comment comment = AutoMapperConfig.mapper.Map<CommentViewModel, Comment>(commentViewModel);
                comment.RegisterDate = DateTime.Now;
                comment.IsActive = false;
                _commentService.Add(comment);
                _commentService.Save();
                return RedirectToAction("ShowComments");
            }
            return PartialView(commentViewModel);
        }
    }
}

hotel/Views/Comment/CreateComment.cshtml
@model hotel.Models.ViewModels.CommentViewModel

@using (Ajax.BeginForm("CreateComment", "Comment", FormMethod.Post, new AjaxOptions
{
    UpdateTargetId = "showMessage",
    OnSuccess = "runMessage"
}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CommentText, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CommentText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CommentText)
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ارسال دیدگاه" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

hotel/Views/Comment/ShowComments.cshtml
@model IEnumerable<hotel.Models.ViewModels.CommentViewModel>

@foreach (var item in Model)
{
    @Html.Partial("_CommentBox", item)
}